// Game types
export const START_GAME_FETCH = "START_GAME_FETCH";
export const START_GAME_SUCCESS = "START_GAME_SUCCESS";
export const START_GAME_ERROR = "START_GAME_ERROR";

export const SAVE_GAME_FETCH = "SAVE_GAME_FETCH";
export const SAVE_GAME_SUCCESS = "SAVE_GAME_SUCCESS";
export const SAVE_GAME_ERROR = "SAVE_GAME_ERROR";

export const RESUME_GAME_FETCH = "RESUME_GAME_FETCH";
export const RESUME_GAME_SUCCESS = "RESUME_GAME_SUCCESS";
export const RESUME_GAME_ERROR = "RESUME_GAME_ERROR";

export const PLAY_FETCH = "PLAY_FETCH";
export const PLAY_SUCCESS = "PLAY_SUCCESS";
export const PLAY_ERROR = "PLAY_ERROR";

// User types
export const LOGIN_USER_FETCH = "LOGIN_USER_FETCH";
export const LOGIN_USER_SUCCESS = "LOGIN_USER_SUCCESS";
export const LOGIN_USER_ERROR = "LOGIN_USER_ERROR";

export const LOGOUT_USER_FETCH = "LOGOUT_USER_FETCH";
export const LOGOUT_USER_SUCCESS = "LOGOUT_USER_SUCCESS";
export const LOGOUT_USER_ERROR = "LOGOUT_USER_ERROR";

export const GET_SUMMARY_FETCH = "GET_SUMMARY_FETCH";
export const GET_SUMMARY_SUCCESS = "GET_SUMMARY_SUCCESS";
export const GET_SUMMARY_ERROR = "GET_SUMMARY_ERROR";
