// Game types
export const START_GAME_FETCH = "START_GAME_FETCH";
export const START_GAME_SUCCESS = "START_GAME_SUCCESS";
export const START_GAME_ERROR = "START_GAME_ERROR";

export const SAVE_GAME_FETCH = "SAVE_GAME_FETCH";
export const SAVE_GAME_SUCCESS = "SAVE_GAME_SUCCESS";
export const SAVE_GAME_ERROR = "SAVE_GAME_ERROR";

export const RESUME_GAME_FETCH = "RESUME_GAME_FETCH";
export const RESUME_GAME_SUCCESS = "RESUME_GAME_SUCCESS";
export const RESUME_GAME_ERROR = "RESUME_GAME_ERROR";

export const PLAY_FETCH = "PLAY_FETCH";
export const PLAY_SUCCESS = "PLAY_SUCCESS";
export const PLAY_ERROR = "PLAY_ERROR";
