spring:
  datasource:
    driver-class-name: org.h2.Driver
    url: jdbc:h2:mem:db;DB_CLOSE_DELAY=-1
    username: sa
    password: sa
    hibernate:
      ddl-auto: update
hibernate:
  types:
    print:
      banner: false
